[workspace]
members = ["protolith-db", "protolith/admin", "protolith/api", "protolith/app", "protolith/auth", "protolith/client", "protolith/core", "protolith/engine", "protolith/error", "protolith/macros", "protolith/tracing"]

